### ISSUE TITLE
Hello add this cheat sheet to awesome-cheatsheet

### ISSUE THREAD

**Issue by detailyang** [joemasilotti/UI-Testing-Cheat-Sheet#10]
Hello, we have indexd this cheat sheet to [awesome-cheatsheet](https://github.com/detailyang/awesome-cheatsheet)

Thank You !!! :rocket: :rocket: :rocket:

**Comment by leopic** [comment]
@detailyang thank you, but this cheat-sheet should be filed under "ios-cheat-sheet", right next to "iOS-App-Performance-Cheatsheet", as it's iOS only

**Comment by detailyang** [comment]
PR welcome :beers:

**Comment by leopic** [comment]
Sent 🍺
