### ISSUE TITLE
Question - Do you have a version for Xcode 8 and Swift 3

### ISSUE THREAD

**Issue by ngtandat** [joemasilotti/UI-Testing-Cheat-Sheet#11]
Hi Joe, 

Thank you for your great UI Testing Cheat Sheet. I am trying to converting it to Xcode 8 but failed with many error in syntax.

Do you have a version of this app for Xcode 8 and Swift 3 ready? If yes, could you share it. 

Thanks again,
Dat

**Comment by leopic** [comment]
Project has been updated to Swift 3 @ngtandat, this one is g2g.

**Comment by joemasilotti** [comment]
Right you are! Thanks again, @leopic.
