### ISSUE TITLE
Forcing system dialogs to appear on every run

### ISSUE THREAD

**Issue by jakovljevic-mladen** [joemasilotti/UI-Testing-Cheat-Sheet#17]
In `func testDismissingASystemAlert() {...}` there is code sample on how to write test for case when system dialog appears (Location Services permission dialog). This code works fine _only_ if run once for the first time on particular device. Reruns are not triggering system dialog to appear (which is understandable - this is how system works).
But this means I can only have one test to see what happens with my app (in this test it is tapping _Allow_ button). There are at least two more cases (besides tapping _Allow_ button) which can be tested: first one is, of course, tapping _Don't Allow_ button; second one is pressing _Home_ button.
Is it possible to rewrite this test so that system dialog appears every time a test is being run?

**Comment by joemasilotti** [comment]
You can try deleting the app between tests to reset the permissions.

https://stackoverflow.com/a/39092323/384110
