### ISSUE TITLE
Finding Search Bar embedded inside a navigation bar in iOS 11.

### ISSUE THREAD

**Issue by n0shake** [joemasilotti/UI-Testing-Cheat-Sheet#20]
This repo has been exceptionally helpful. Thanks for making this.

I've been running into a pickle especially while testing search on VCs in iOS 11 where the search bar is embedded inside a navigation bar. Neither `app.searchFields` or any child element under `app.navigationBar` reveal the relevant `XCUIElement`. 

Is there a workaround for this?

**Comment by leopic** [comment]
Hello @n0shake 

Did you ever manage to get this working? I'm curious

**Comment by joemasilotti** [comment]
What kind of output does the Accessibility Inspector give you? You might be able to set an accessibility identifier in code then reference it via that string.

**Comment by joemasilotti** [comment]
@n0shake, I'm going to close this issue since it is over 2 years old. If you have any updates, especially for iOS 13 or 14, feel free to reopen it.
