### ISSUE TITLE
Webview Test Elements

### ISSUE THREAD

**Issue by bichoec** [joemasilotti/UI-Testing-Cheat-Sheet#24]
Hello! I think it's not the best place to ask this question but I was trying to figure out the issue.
I was testing (XCUITest) a Webview (Load an Angular Page). I ran the test with this code line:

`let propertiesButton = app.webViews.otherElements.element(boundBy: 3).firstMatch`
`if propertiesButton.exists {`
`    propertiesButton.tap()`
`}`

Properties Window opened fine only in Simulator **iPhone 11 - 13.1**. If I run the same test with another Simulator like **iPhone 11 Pro - 13.1 or 13.3** the tap() doesn't work.

Also this line: `app.swipeUp()` when the Properties Window is opened, only works in Simulator **iPhone 11 - 13.1**

I'm not sure if the issue will be from how the web view render the Angular page (CSS).
Does anybody have or had the same issue?

**Comment by joemasilotti** [comment]
I've seen the `swipeUp()` method not work on larger screen sizes. For example, calling `swipeDown()` won't dismiss a sheet on some devices. I recommend filing a bug with Apple.
