### ISSUE TITLE
Question - Does the DismissingASystemAlert work on an actual device or just the simulator

### ISSUE THREAD

**Issue by ghost** [joemasilotti/UI-Testing-Cheat-Sheet#5]
I was using your example and it works great on the simulator but I am not able to get the alert to be dismissed on an actual iPad Air 2 device.  I think I remember reading somewhere that alerts are not being dismissed on ipad devices - only phones.

**Comment by joemasilotti** [comment]
Unfortunately I don't have an iPad to run these tests against.

However, I was able to verify that the alert can be successfully dismissed on:
- iPhone Simulator
- iPad Simulator
- iPhone 5s

**Comment by ghost** [comment]
I pulled the latest code and the system alert is being dismissed when I run the test on the ipad air2 device.  Thanks
