### ISSUE TITLE
How to search for element using regular expression?

### ISSUE THREAD

**Issue by onmyway133** [joemasilotti/UI-Testing-Cheat-Sheet#8]
Hi, for example, I know there will be a label named "This belongs to [someone]". The [someone] text will be dynamic, I know that there will be only one, how to find this label?

**Comment by leopic** [comment]
I believe you can use `NSPredicate` here, something along these lines http://stackoverflow.com/questions/3590254/how-to-find-beginswith-word-in-a-string-using-nspredicate 

I would combine that with https://github.com/joemasilotti/UI-Testing-Cheat-Sheet#waiting-for-an-element-to-appear

**Comment by joemasilotti** [comment]
Right on, @leopic! The [Interacting with pickers](https://github.com/joemasilotti/UI-Testing-Cheat-Sheet#interacting-with-pickers) section has another example, too.

``` swift
let predicate = NSPredicate(format: "label BEGINSWITH 'This belongs to'")
let label = app.staticTexts.elementMatchingPredicate(predicate)

let exists = NSPredicate(format: "exists == true")
expectationForPredicate(exists, evaluatedWithObject: label, handler: nil)

waitForExpectationsWithTimeout(5, handler: nil)
XCTAssert(label.exists)
```

**Comment by onmyway133** [comment]
@joemasilotti @leopic many thanks :+1:

**Comment by leopic** [comment]
@joemasilotti is this still a valid issue or is this g2g?

**Comment by joemasilotti** [comment]
@leopic good to go, closing now.
